export const lighthouseIcons = {
  logo: "solar:map-point-wave-bold",
  heart: "solar:heart-bold",
  mirror: "solar:book-2-bold",
  action: "solar:bolt-bold",
  workshop: "solar:clipboard-check-bold",
  hermit: "solar:magic-stick-3-bold",
  search: "solar:magnifer-linear",
  send: "solar:plain-bold",
  edit: "solar:pen-2-bold",
  delete: "solar:trash-bin-trash-bold",
  publish: "solar:upload-square-bold",
  reject: "solar:undo-left-round-bold",
  save: "solar:diskette-bold",
  close: "solar:close-circle-bold",
  pin: "solar:pin-bold",
  unpin: "solar:pin-circle-bold",
  menu: "solar:sidebar-minimalistic-bold",
  bell: "solar:bell-bold",
  more: "solar:menu-dots-bold",
  refresh: "solar:refresh-bold",
  add: "solar:add-circle-bold",
  document: "solar:document-text-bold",
  status: "solar:check-circle-bold",
  warning: "solar:danger-triangle-bold",
  info: "solar:info-circle-bold",
} as const;

export type LighthouseIconName = keyof typeof lighthouseIcons;
